# create a Headless Service for Elastic Serach
# This will create a headless service for our Elasticsearch stateful set of 3 replicas. 
# A headless service will basically define a DNS, it will not create a cluster Ip address and will not load balance.
# Kube-proxy does not handle this services.
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node

