# create Storage Class “local-storage”
# This will create a storage class with provisioner as “docker.io/hostpath” 
# and volume binding mode as “WaitForConsumer” which means 
# it will delay the persistent volume creation till the pod is ready.
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: docker.io/hostpath
volumeBindingMode: WaitForFirstConsumer