apiVersion: v1

name: ibm-mq-test-injector

description: A Helm chart for Kubernetes



# A chart can be either an 'application' or a 'library' chart.

#

# Application charts are a collection of templates that can be packaged into versioned archives

# to be deployed.

#

# Library charts provide useful utilities or functions for the chart developer. They're included as

# a dependency of application charts to inject those utilities and functions into the rendering

# pipeline. Library charts do not define any templates and therefore cannot be deployed.

type: application


name: efk
sources:
- https://hub.docker.com/_/fluentd
- https://hub.docker.com/_/elasticsearch
- https://hub.docker.com/_/kibana

# This is the chart version. This version number should be incremented each time you make changes

# to the chart and its templates, including the app version.

version: 1.0.0
apiVersion: v1
appVersion: 1.0

version: 1.0
