apiVersion: v1
appVersion: 1.0
description: Official Elastic helm chart for Kibana
name: efk
sources:
- https://hub.docker.com/_/fluentd
- https://hub.docker.com/_/elasticsearch
- https://hub.docker.com/_/kibana
version: 1.0
